@BASE_URL=http://localhost:3000

### Register User

POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
    "username": "chloeda",
    "email": "chloeda@gmail.com",
    "password": "Azerty@89",
    "confirmPassword": "Azerty@89"
}

### Login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "identifier": "chloeda",
    "password": "Azerty@89"
}