@BASE_URL=http://localhost:3000



POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "username": "cloee",
    "email": "cloee@ample.com",
    "password": "Ccccccccc@8",
    "confirmPassword": "Ccccccccc@8"
}

### Login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "identifier": "cloee",
    "password": "Ccccccccc@8"
}