### inscriptions
POST http://localhost:3000/localhost:3000/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "testpassword",
    "confirmPassword": "testpassword"
}